-- MySQL Script generated by MySQL Workbench
-- Sat Apr 17 22:40:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE Company(
	companyId INT NOT NULL auto_increment,
    companyName varchar(255) not null,
    avatarUrl varchar(255) not null,
    location varchar(255) not null,
    description varchar(255) not null,
    phoneNumber varchar(255) not null,
    primary key (companyId)
);

CREATE TABLE User (
	uid INT NOT NULL auto_increment,
    nickname  VARCHAR(255) NULL DEFAULT NULL,
    created_at TIMESTAMP default now(),
    gender enum("Male","Female"),
    location VARCHAR(255) NULL DEFAULT NULL,
    phoneNumber VARCHAR(255) NULL DEFAULT NULL,
    email VARCHAR(255) NULL DEFAULT NULL,
    avatarUrl VARCHAR(255) NULL DEFAULT NULL,
    password VARCHAR(255) NULL DEFAULT NULL,
    company int, 
    primary key (uid),
    foreign key (company) references Company(companyId)
);

CREATE TABLE Payment (
	creditNum VARCHAR(255) NOT NULL,
    expireDate DATE NOT NULL,
    amount DECIMAL(19,0) NOT NULL,
    user int,
    primary key (creditNum),
    foreign key (user) references User(uid) on delete cascade
);

CREATE TABLE OrderStatus(
	statusCode int not null,
    statusText VARCHAR(255) NULL DEFAULT NULL,
    statusColor VARCHAR(10) NULL DEFAULT NULL,
    statusDesc VARCHAR(255) NULL DEFAULT NULL,
    primary key (statusCode)
);

CREATE TABLE HoaDon(
	id INT NOT NULL auto_increment,
    created_date date default now(),
    shipping_time timestamp not null,
    shipping_address VARCHAR(255) NULL DEFAULT NULL,
    payment_method enum("Credit Card","COD") not null,
    statusCode int,
    comments VARCHAR(255) NULL DEFAULT NULL,
    creditCard VARCHAR(255) NULL DEFAULT NULL,
    user int,
    primary key (id),
    foreign key (statusCode) references OrderStatus(statusCode)  on delete cascade,
    foreign key (creditCard) references payment(creditNum)  on delete cascade,
    foreign key (user) references User(uid)  on delete cascade
);

CREATE TABLE Promotion(
	promotionId INT NOT NULL AUTO_INCREMENT,
    promoCode VARCHAR(20) NULL DEFAULT NULL,
    promoPercent SMALLINT NULL DEFAULT NULL,
    expireDate timestamp,
    promoDescription VARCHAR(255) NULL DEFAULT NULL,
    primary key (promotionId)
);

CREATE TABLE Product(
	id int not null auto_increment,
    productName VARCHAR(255) NULL DEFAULT NULL,
    price decimal(19,0) not null,
    productType enum('Đông lạnh', 'Tươi sống', 'Đồ khô', 'Khác...'),
    posted_at timestamp default now(),
    company int,
    description VARCHAR(255) NULL DEFAULT NULL,
    promotion int,
    likes int default 0,
    pricePerRatio ENUM('kg', 'g', 'chiếc', 'con') NULL DEFAULT NULL,
    imageUrl VARCHAR(255) NULL DEFAULT NULL,
    primary key (id),
    foreign key (company) references Company(companyId)  on delete cascade,
    foreign key (promotion) references Promotion(promotionId)  on delete cascade
);

CREATE TABLE Product_hoadon(
    hoadon int,
    qty int,
    product int,
	foreign key (hoadon) references HoaDon(id),
    foreign key (product) references Product(id)
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
